#!/bin/bash

############################################## About Author #########################################
# Created by: Alsamman M. Alsamman                                                                  #
# Emails: smahmoud [at] ageri.sci.eg or A.Alsamman [at] cgiar.org or SammanMohammed [at] gmail.com  #
# License: MIT License - https://opensource.org/licenses/MIT                                        #
# Disclaimer: The script comes with no warranty, use at your own risk                               #
# This script is not intended for commercial use                                                    #
#####################################################################################################


################# To print error
#TOOL INPUT > OUT 2>error
#################

#Activate Conda
#eval "$(conda shell.bash hook)"
#conda activate base




# read the scriptconfig file
targetScript="fasta2Table.py"
Compiler="python3"
variablePath="AlsammanUbuntuMenuScriptsPath"
ScriptSubFolder=Functions/

#### Prepare the script full path
# get the environment variable of $AlsammanUbuntuMenuScriptsPath from ~/.bashrc
AlsammanUbuntuMenuScriptsPath=$(grep -oP '(?<='$variablePath'=).*' ~/.bashrc)
scriptFullPath=$AlsammanUbuntuMenuScriptsPath$ScriptSubFolder$targetScript
# remove the quotes from the path
scriptFullPath=$(sed -e 's/["'\'']//g' <<<"$scriptFullPath")
####

echo -e "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | while read line
do
if [ ! -z "$line" -a "$line" != " " ]; then

$Compiler $scriptFullPath $line $line".tsv" 

fi
done
