#!/bin/bash

############################################## About Author #########################################
# Created by: Alsamman M. Alsamman                                                                  #
# Emails: smahmoud [at] ageri.sci.eg or A.Alsamman [at] cgiar.org or SammanMohammed [at] gmail.com  #
# License: MIT License - https://opensource.org/licenses/MIT                                        #
# Disclaimer: The script comes with no warranty, use at your own risk                               #
# This script is not intended for commercial use                                                    #
#####################################################################################################

################# To print error
#TOOL INPUT > OUT 2>error
#################

# remove duplicate lines by using first column
# scriptname is

echo -e "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | while read line
do
if [ ! -z "$line" -a "$line" != " " ]; then

filename="$line"

    # remove duplicate lines by using first column
    awk '!seen[$1]++' $filename > $filename.tmp && mv $filename.tmp $filename\_"uniq"

fi
done 












