#!/bin/bash


# This script adds the filename as the last column


echo -e "$NAUTILUS_SCRIPT_SELECTED_FILE_PATHS" | while read line
do
if [ ! -z "$line" -a "$line" != " " ]; then
    if grep -q $'\t' $line; then
        awk -F'\t' -v OFS='\t' '{$(NF+1)=FILENAME; print}' $line > $line.tmp
        # remove full path and keep only filename
        filepath=$(echo $line | rev | cut -d'/' -f1 | rev)
        sed -i "s/$filepath//g" $line.tmp
        mv $line.tmp $line
    else
        awk -F',' -v OFS=',' '{$(NF+1)=FILENAME; print}' $line > $line.tmp
        filepath=$(echo $line | rev | cut -d'/' -f1 | rev)
        sed -i "s/$filepath//g" $line.tmp
        mv $line.tmp $line
    fi
fi
done 












